name: "Docker Lint"

on:
  workflow_call:

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: Run Dockerlint
      run: |
        wget https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64 -O hadolint
        chmod +x hadolint
        ./hadolint Dockerfile
