name: "Gradle Publish"

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY:
        description: 'AWS Access Key'
        required: true
      AWS_SECRET_KEY:
        description: 'AWS Secret Key'
        required: true      
      AWS_REGION:
        description: 'AWS Region'
        required: true
      AWS_CODEARTIFACT_DOMAIN:
        description: 'AWS CodeArtifact Domain name.'
        required: true
      AWS_ACCOUNT_ID:
        description: 'AWS Account ID'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: 18
          distribution: 'adopt'

      - name: Build with Gradle
        run: |
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ${{ secrets.AWS_CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --query authorizationToken --output text`
          ./gradlew -Pversion=${GITHUB_REF##*/} publish
